### ISSUE TITLE
Show some example in the README

### ISSUE THREAD

**Issue by Melkaz** [koesterlab/alignoth#2]
Hello,

I'm quite interested in your project but I think it would be nice to have an idea of the output plots in the README.

Have a nice day :)

**Comment by fxwiegand** [comment]
Hi,

thanks for your input! I also already thought about an example plot in the REDAME but didn't have the time to do it. We only made the repo public yesterday. Until we add the example [here's one](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQUOQDMaZNKEHk4sgCZaQgpAE82DTEYBOGrEaSzYba2hARMSa1aVQ9mOFdUVSRBCDglfRprOChMdnl0GBcaAC85T0FFEGRrWkSARgAGAF8yksikT3DMCCMYO2Eye1QAbQBdJRikfTq20CgNLzcCgF4AHwKAYUmJ6dnJgEFJgHEFgrWx1fGAZjnN5a2Cw7nlgCZT3bmZgoAVcbObk8mbuev15YA2C+zVEzI+gAOHZKZA4ACOaDOIJyODYfQKnyKOzEgKUsiQCDgbgAygAlPFFb6fHYAFkoBVJAE5SZ9STsqdk4RA6Ak0IiiqSAOxnLpsADu7IqAyGQRAZ1Jly5YlGv3+QJhYMhqGhoOZ7KRO0+XPRmOx6HxhOJZMo1LOYiKVIKTPhrLkGs5gLRIGsAqhwuUopGkqW40BMrlSABaCpVNBSAhaB2Oth8IdqOdGKxuIJRLOJPJxTOiOhRRtLPi9tQHOpztdgtQOw9gwoYsBlytsqUfyDfVD4cjlZjCHVxaRCd1yYNqeJpIKFM5qKKZ0ZSmZdsK-c5fIrpOrXvQMt9NKbIBbwdQ7ZyEeV0bVcb7RVRn0H+pAhrTJIkBStFp5pPzC-jRRj5bQYnXWsRiKIpd33BFuQ7ZUziKc8ESRWkClvFMjXTMdKC5AouW5a051tQtFyvMkVzQT5AOGdBilAwMD0RRUTyhWDY3gq9pWQ4dUIzCkqQtMRPhpT8CPjLUSNQLlyLFKiwPlEMw2PTsYLgh1PjEGEkzvB9jUzRFPgQsRBLZS8xD40TAQk4DqObGTUGBKD2V5ZjhJvEB1JQx8TRfXj+I-PCC0MjkxDYl03TE8zKJA6TW3ZSD5OguSewvAKf3Y+8R3TFFuIKN8JQMosAsBZy-1QACFBFIDwssvdrMpbsGJVeLexLKlEz1NytInbNvh2PNfK-IynVEqtSs9cqQCkmiINqzsRMcozlxc1qOMfdDilJKcZ1ywiB2C1cwrGiKJo1ejOyYhKWO1ZzXKW9quV0p0QM25T5qKgo9vGqyosPeK6u7RqkS5HY1MW1LOJNGDASpFS6Uey8SV-EKzjeg6PtomKlXspSjJMhahxB9ztN0vSYY5FSYSKszhprCj9sq8C0Fs2K0FOv6iXmq68Zuu7AQe3qhNh27RNeymNxpyLaJJOzizETGOUBF8Us0tDx2KVS31wkB5z5jkeSYoqhrK6n3qqz6aslrKZaROGFbSrjwchvifI1-D-P+wHRMR4XRqNumvrN6XZtlolrdBzMQM+AqCuJ13CpCtdPcN5HjYPI90ali2igj4P8coaFMJ5LlASjn8uXhisSoNsV+PeCUJi3O5DuLApVUZtOA6RTOcY0m2wejLCdiwouS9L0i3vuUMxfg47lWZxL28BGN2cVp8c+RNNAsHnjBb2qkLl9LkJ+iqblV+2efxmxfu9DokI8+IvuZj3b48kxOfYZ1OT5YnWs9HZWiLVu-5Y7SjHtHY9ZJj3E+GMBuKc6ozxYlaFquMl4eSpDsc0XIBK8xdhnYy7ska02sjAk66dUGXWBsgiQwIrzeTvt8US4kn4WQPsWNGP105D2-ulckucsJnALrQssIVy4jWpumS4WFLjGWYQULCSEW4fwdBwzubUuE517gDAeWC8rt3DqJMijCKrMLfrA9hm9lHXXShIGC3Vvjry0YRJ0w9iz4OYUQ6eJCBbmI5krCkgV+50TvhDUyJROgujgKoQIeg-A2HCZEpwd4piLBWFMW4STEkrBWLcFYixEm3Dyck1JqSMnZMyUkjJSSclFPKYU7JtwUlZJSckxYiw6l5LqbktpSTUnNNac0nJXTMnZJaVMDpjS2lTEySMkZlTpkpOmSU6ZfTEkVL6XUnphSWl5JSV01peS+nNNycM7p2yem5JOXsvptSektKaVkzJ7SWkzO6c0oZBy9lZPaQ0x5ay7n9LabUoZDT3lrPudkxpgyimVJBd045Yy1k3I6Qi9JNzTn5LOfCl5kL+nXPyVs8ZOzcXbKmY8npTTvl7POYsbIHgvBWDmqUCoIAolsCiLITQqBQAAA8HCcpoH0UA8RMA6DcJrNkjL1BwEEIYdANLvDUqgKEfUoB9BsGQDQRIrQmpUkoNLWWoYdXtEZZgUwOA7zggYI4QVVQaCkBAIyzlZwjASqlW4PQhglDGtNW4c1lq6DWttYy0wPK+VoFkAwQQghmw0EldKoBHqTV3hcKy0IdrGXwDsHSnkSgTCmECGgVoyqqgoA5V4hozQmj2EZcy1l7KBhsEEC4IwxBQgMDvDEQwjK2A4CQIMY1TaW36iKL4wNjqS3NsEK29kIFp0gTKOGawABrNwMQ4h2uGvoItRh2YxAiTEeJa6mVOBZeq2tyh62NpLc62NTAkDhGyDoMgbrQ3hsje4BVwqS0qrVRqkAVKlBTGyCsbItxsgADlsjIEwLAbI+hJVwCEkodV4RvBslCdYRwj780gAAMSJIACIACF+LZGwwAMTOERzCJHyOAhGY6pQ2GeSAlJIsQuDHFjQgAKIyJIwRvj-GSMjMpJSEjnIuRTCKFS0JnrE3WGTVkOd7hMCugXXAAA6jQfQ9B+0Tv1CVEAmA2D1viDgfNoAr1uBvXekJjLchLpLVAYQpnUDKdbfGr16BrDhuxIy7t6GEB9ALSAJg6rY3QEVXUFKZBbDuvcHB1d6B1UBGsOOu10n0OyAgKoFwCAzMgFvZZ292JfChCgOGqod4IA4GEJgAAFBuzADAECUB3XEvwCgAAEAByLrABKNdoACvoDYKoVQNRsjvrKyYAIbhwjmqiXAerVQmstdiXuvwlAdBsvoP1j0LZsB6Cw1Z4rIARtjfgyAQ1w0htOz8vaErggpsVbcA1lbsrMAdYANQdde81s742PQ3fexN0r5WZvoF+5QUVcgOv8A60O-SgO+iHti5NsHd5IfQ9kF9+HOq0sega8W0A264A9DqFWo9NajAqAbUEcz0aXXoHRkocLH7lWqqQOq-NSIFBFDQxh-UrQcNWhnSRqAXJp30Zw6N0XDHRvSh5tL1QTAYI9SV3AHe6tsNMB17ry7RqE3eotbIK18QA0s+U2wVTGmtMwCdQz2NMn726AMM+iNLP31KpAF+znP6-0gAA0oIDSgQNKHA+GKDdvIhwYQyAJDgQhL87ZYL6WqeFBp7T4CaThvhtyfVSm8o877MDCc2gVzEQDM55dN5g9ynHBZZy3lm7VNrCReUKD6blXqt0CW415rLfOtdfGH1gb+Xkct4APqhbgNyh7T3wdxfm-E3vK2W8QE23oMgO3R-7YCD+tfE3RRT4MDP-X13kdO7n+jtwNBVC1YgMwDwtg2Ur-76KCAnXYIdYKL1jroxRjdY0BdaD7x4oZyDAEda3736P7KYnqv6UBr6dZbZb4wDwFr6-5w5IQdbIH0BoHv69a-7-7dajAQFdaQawAQFQEP5MBP5wGQ6IHYGb64H0H4Gw7f5IFMGoEsG1gQAEF-4AFdb6CkGwY6AEQQHUG0Ev7cFeAf7sGMHbZcHLZv48EEGqGj43Y4FR7t6PbX6JZ36Q4yb8HdbkEwBdYdbjDjA-ZKGUCGFEGCEx4JAQF+bhAACSJu0BNBsBUh1hDBX+mheBKhbBP+vWnWUBBhCaRhXWoBYhnWWBzhcAbhdWEhXhZAARMhn+HBChaRreGB3+qhu25+bg-2F2Sg0WFgOATAQabQyivgXo9il2FuPa9mxgnB6hyOwOV+neN++h1hthAh0RjhnWmOzsMO32kOxRmAQx1hWOOO4xo2NQbBQ6XIBRg2yOT6nRz2eh8BfRgBmWCegxVhfeUOIx2OYx1hExsx1hmhUxRxMxZxRxFx9xK2mhOOSxu2V2hangW6wM3QvQB61aJ61O56dOIA46k66A2G-GAmjKT+Vu6mmm2mY6A6QotmXgxeygpeLmXmFeTunmNeRqGWDe1guW-QY+s2ngcqGxC+YR0xJxHWAAPIcStmdDcStjMXDgjqyc1mdIsTqisWSegOsdofPneDSbcXSQAHxMncnMhcnHF3bY4ck6pyk8lKliDvEE6bolok5k7-GU6AkObAn24xpuCX4tGPqu4loQCmAIBMD1o4hpD6hBSCofruA2l2kKYe6KpGA+5c7VH+6B4gDB4gCh4gDh7HiR4wYOH3Zx57FgHyBJ6YbVG4aLCEbEYMbkaUZa40Z0YkZMYsZsY4YcY7DcZa5Ql8aCZTDCaOzYZiYSZSbuaybyapoW4qbwm27GmM6V5erZou7Sphru5vremfoc5+lC4BmAbAZgYQZVDQbR6iFsiIZxmJ5dAC75oggbkKCbmbmfDZ4eanZ54YgKZGpGaCAmZ5YWboCuR7YO6mmG43kmlM4MQPldl0w2ZF7U6Ynl6NnLr4keqEnZbElN7I50xUl3iSBsDqq1atC34da1bwHgQdYABkeRHWUpX+XWvxHW3a0QcA+gg+g+fWoRqgcFCF8oyFHWZwv+6Fg+WFYIpq+gkB2OOAropq1g2FnO1gBF3WRFHWkBJF8FkOiFKFpI1F8OtFpOjFDAsg9FeF3FPWIR-FpFQl5FKFgIYlGFkGcAHW0lsl+F3WhFilsFgl1hwl3+nwGlElPQHWMQpAre2lT+jg+lpBvFxlZFrYFFaCllxhFWNlcAdl4QHWjlBg8lrlAl7lAIFFdI3lXW6greH26qHF0QoVRl4VKlHlKFTc6laF4l3W4QKgBgTFSVXFBlPFqVylplqllFfEMVsgbAH2LFNAuQpgHWoQGgMl-gKVxFFVRxZlYgTcMVWFIQNAYQ2F02gFCAvABgLgHWPqNWLVsAsQC6shLl5VJlvVVVWYolOVGFWFfKHWAAClMHiB1jNV2vEO+j9gwN3gqgEF1UpetStmZTBKSNlTRXldddVogP4F4C1W1WQB1SbilZ0GVW0W4AfmBbNt3nVtISVUPiPkjuDUftPrPsKboYvq2svrDevpofybvodtURDSItYMfrBtyh8QKd2Sdmjl0Vsckc-qkdjRkahXYUASAcuQcVQTAQzdkbIf4djbkVgfzT4fgYQQISQYPiYZQXfvTXQSLTwZkSgbzYLYrcwfLTIXwXYUIYPiIfBgcbLd4UcQwULZwcrfkWDegJoSDjobTXHj0UcTsWQbOaYeYZYeEaapEbrTERxfZYkR4ZIYzera3szcLUbawZgQQcRdsREazRzeAbEZ1vEX7QbYHWHQrblaHavuHXkWoYjcNvMSUSAGUddZUVhq5LUUBPUaEjSlAM0VbXnUprStbSKd0dHR7bHcht7cMQqZcQ8QXZMdKfKQuL3SthcWqfyTdkKTTZsXbW3dpR3fsfHYPXcYPY8YPdccvXSU8X9v3SPc1i8d9gjhqWhnADIIILalaZ7kYLCdbgiXbolifqaifibi2SAPyHfVOhKCUEAA) where you can see the interactive features (like tooltips, zooming and panning in the plot) and here's a static svg:
![visualization-3](https://user-images.githubusercontent.com/39430842/174983222-d9007971-0f8b-4871-85f8-55284f4bd606.svg)
